pr: none
trigger: none

jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      matrix:
        ubuntu2004:
          image: symless/synergy-core:ubuntu20.04
          packager: deb
          name: ubuntu20

    container: $[ variables['image'] ]

    steps:
      - template: CI/checkout.yml
      - template: CI/Linux/linux-build.yml